---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(dplyr)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
data(ny_noaa)
ny_noaa=ny_noaa %>% 
  drop_na() %>% 
  mutate(
    tmax=as.numeric(tmax),
    tmin=as.numeric(tmin)
         )
ny_noaa %>% 
  mutate(
    year=format(date, "%Y"),
    year=as.numeric(year)
         ) %>% 
  filter(snow>0 & prcp>0 & year== 2010) %>% 
  mutate(text_label = str_c("Snowfall(mm):", snow, "\nSnow Depth(mm): ", snwd,"\nPrecipitation (tenths of mm): ",prcp)) %>% 
  plot_ly(
    x=~snwd,y=~snow,type="scatter",mode="markers",color=~prcp,text = ~text_label,alpha=0.7,opacity=0.7
  ) %>% 
  layout(
    title = "Snowfall vs Snow Depth (2010)",
    xaxis = list(title = "Snow Depth (mm)"),
    yaxis = list(title = "Snowfall (mm)")
  )

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
ny_noaa %>%
  mutate(
    year_month = format(date, "%Y-%m"),
    year = as.numeric(format(date, "%Y")),
    tavg = (tmax + tmin) / 2
  ) %>%
  filter(year == 2010) %>%
  plot_ly(x = ~year_month, y = ~tavg, color = ~year_month, type = 'box',colors = "viridis") %>% 
  layout(
    title = "Monthly Average Temperature in 2010",
    xaxis = list(title = "Date"),
    yaxis = list(title = "Average Temperature (C)")
  )  
```

### Chart C

```{r}
ny_noaa %>% 
  group_by(date) %>% 
  summarize(mprcp=mean(prcp)) %>% 
  plot_ly(x = ~date, y = ~mprcp, type = "scatter", mode = "lines") %>%
  layout(
    title = list(text = "Average Daily Precipitation Over Time"),
    xaxis = list(
      title = "Date",
      showgrid = FALSE
    ),
    yaxis = list(title = "Average Precipitation (tenths of mm)")
  )
```

